"""empty message

Revision ID: 14543e346e36
Revises: 5be60d78096d
Create Date: 2022-08-03 21:12:39.559649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14543e346e36'
down_revision = '5be60d78096d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('ability', sa.String(), nullable=True),
    sa.Column('exp', sa.String(), nullable=True),
    sa.Column('attk', sa.String(), nullable=True),
    sa.Column('hp', sa.String(), nullable=True),
    sa.Column('defense', sa.String(), nullable=True),
    sa.Column('sprite', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date_caught', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemon')
    # ### end Alembic commands ###
