"""empty message

Revision ID: 5e404bb34e31
Revises: 8bd6c26393a7
Create Date: 2022-08-07 15:50:53.937557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e404bb34e31'
down_revision = '8bd6c26393a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('wins', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('loses', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'loses')
    op.drop_column('user', 'wins')
    # ### end Alembic commands ###
