"""empty message

Revision ID: 8bd6c26393a7
Revises: 
Create Date: 2022-08-05 15:37:14.329554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bd6c26393a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ability', sa.String(), nullable=True),
    sa.Column('exp', sa.String(), nullable=True),
    sa.Column('attk', sa.String(), nullable=True),
    sa.Column('hp', sa.String(), nullable=True),
    sa.Column('defense', sa.String(), nullable=True),
    sa.Column('sprite', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('icon', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('team',
    sa.Column('trainer_id', sa.Integer(), nullable=True),
    sa.Column('pokemon_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pokemon_name'], ['pokemon.name'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('pokemon')
    # ### end Alembic commands ###
